/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_Texto(xdrs, objp)
	XDR *xdrs;
	Texto *objp;
{

	if (!xdr_string(xdrs, objp, 100))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Operandos(xdrs, objp)
	XDR *xdrs;
	Operandos *objp;
{

	if (!xdr_int(xdrs, &objp->op1))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Resultado(xdrs, objp)
	XDR *xdrs;
	Resultado *objp;
{

	if (!xdr_int(xdrs, &objp->caso))
		return (FALSE);
	switch (objp->caso) {
	case 1:
		if (!xdr_int(xdrs, &objp->Resultado_u.n))
			return (FALSE);
		break;
	case 2:
		if (!xdr_float(xdrs, &objp->Resultado_u.x))
			return (FALSE);
		break;
	case 3:
		if (!xdr_Texto(xdrs, &objp->Resultado_u.error))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}
