#!/bin/bash

echo 'Ejecutando compilador miligramos...'



if [ -d "./ejecutables" ]; then
  echo "Moviendo ejecutables a la carpeta"
  mv *.mg ejecutables
else
  echo "El directorio ejecutables no existe, se procede a crear"
  mkdir ejecutables
  mv *.mg ejecutables
fi

for file in *.c; do
    executable="${file%.*}"
    gcc $file -o $executable.mg -w 
done
