/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIPOS_H_RPCGEN
#define _TIPOS_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


typedef char *Texto;
#ifdef __cplusplus
extern "C" bool_t xdr_Texto(XDR *, Texto*);
#elif __STDC__
extern  bool_t xdr_Texto(XDR *, Texto*);
#else /* Old Style C */
bool_t xdr_Texto();
#endif /* Old Style C */


struct Persona {
	Texto nombre;
	int edad;
};
typedef struct Persona Persona;
#ifdef __cplusplus
extern "C" bool_t xdr_Persona(XDR *, Persona*);
#elif __STDC__
extern  bool_t xdr_Persona(XDR *, Persona*);
#else /* Old Style C */
bool_t xdr_Persona();
#endif /* Old Style C */


struct Resultado {
	int caso;
	union {
		int n;
		float x;
		Texto error;
	} Resultado_u;
};
typedef struct Resultado Resultado;
#ifdef __cplusplus
extern "C" bool_t xdr_Resultado(XDR *, Resultado*);
#elif __STDC__
extern  bool_t xdr_Resultado(XDR *, Resultado*);
#else /* Old Style C */
bool_t xdr_Resultado();
#endif /* Old Style C */


struct Lista {
	int dato;
	struct Lista *siguiente;
};
typedef struct Lista Lista;
#ifdef __cplusplus
extern "C" bool_t xdr_Lista(XDR *, Lista*);
#elif __STDC__
extern  bool_t xdr_Lista(XDR *, Lista*);
#else /* Old Style C */
bool_t xdr_Lista();
#endif /* Old Style C */


#endif /* !_TIPOS_H_RPCGEN */
